<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
require APPPATH . '/libraries/REST_Controller.php';

class Order_detail extends REST_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_detail_model');
    } 

    /*
     * Listing of order_detail
     */
    // function index_get()
    // {
    //     $data['order_detail'] = $this->Order_detail_model->get_all_order_detail();

    //     $this->load->view('order_detail/index',$data);
    // }

    /*
     * Adding a new order_detail
     */
    function index_post()
    {   
        $data = $this->input->post();
        $insert = $this->Order_detail_model->bulk_insert($data);
        if($insert) {
            $message = ['message'=> "created", "code"=> true];            
			$this->set_response($message, REST_Controller::HTTP_CREATED);
        }else{
            $message = ['message'=> 'failed to insert data', 'code'=> false];
			$this->set_response($message, REST_Controller::HTTP_CREATED);
        }
    }  

    /*
     * Editing a order_detail
     */
    function index_put($id)
    {   
        // check if the order_detail exists before trying to edit it
        $order_detail = $this->Order_detail_model->get_order_detail($id);
        
        if(isset($order_detail['id']))
        {
            $data = $this->request->body;

            $this->Order_detail_model->update_order_detail($id,$data);            
            $message = ['message'=> "updated", "code"=> true];            
            $this->set_response($message, REST_Controller::HTTP_CREATED);            
        }else{
            $message = ['message'=> 'invalid ID', 'code'=> false];
            $this->set_response($message, REST_Controller::HTTP_NOT_FOUND);
        }
    } 

    /*
     * Deleting order_detail
     */
    function cancel_delete($id)
    {
               // check if the order_detail exists before trying to edit it
        $order_detail = $this->Order_detail_model->get_order_detail($id);
        
        if(isset($order_detail['id']))
        {
            $data = array('is_deleted'=> true);
            $this->Order_detail_model->update_order_detail($id,$data);            
            $message = ['message'=> "canceled", "code"=> true];            
            $this->set_response($message, REST_Controller::HTTP_CREATED);            
        }else{
            $message = ['message'=> 'invalid ID', 'code'=> false];
            $this->set_response($message, REST_Controller::HTTP_NOT_FOUND);
        }}
    
}
