<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Meja_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get meja by id
     */
    function get_meja($id)
    {
        return $this->db->get_where('meja',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all meja
     */
    function get_all_meja()
    {
        return $this->db->get('meja')->result_array();
    }
    
    /*
     * function to add new meja
     */
    function add_meja($params)
    {
        $this->db->insert('meja',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update meja
     */
    function update_meja($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('meja',$params);
        if($response)
        {
            return "meja updated successfully";
        }
        else
        {
            return "Error occuring while updating meja";
        }
    }
    
    /*
     * function to delete meja
     */
    function delete_meja($id)
    {
        $response = $this->db->delete('meja',array('id'=>$id));
        if($response)
        {
            return "meja deleted successfully";
        }
        else
        {
            return "Error occuring while deleting meja";
        }
    }
}
