<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by id
     */
    function get_menu($id)
    {
        return $this->db->get_where('menu',array('id'=>$id))->row_array();
    }

    function get_menu_by_parent_id($id)
    {
        return $this->db->get_where('menu',array('parent_id'=>$id))->result_array();
    }
    
    /*
     * Get all menu
     */
    function get_all_menu()
    {
        return $this->db->order_by('parent_id', ' DESC')->get_where('menu', ['parent_id IS NOT NULL'=> null])->result_array();
    }
    
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('menu',$params);
        if($response)
        {
            return "menu updated successfully";
        }
        else
        {
            return "Error occuring while updating menu";
        }
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($id)
    {
        $response = $this->db->delete('menu',array('id'=>$id));
        if($response)
        {
            return "menu deleted successfully";
        }
        else
        {
            return "Error occuring while deleting menu";
        }
    }
}
