<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order by id
     */
    function get_order($id)
    {
        $this->db->select('order_detail.id, menu.menu, notes, is_additional_menu, order_detail.price, SUM(order_detail.jumlah) as jumlah');
        $this->db->from('orders');
        $this->db->where(['orders.id'=> $id, 'order_detail.is_deleted'=> false]);
        $this->db->group_by('order_detail.menu_id');
        $this->db->join('order_detail', 'order_detail.order_id = orders.id', 'right');
        $this->db->join('menu', 'menu.id = order_detail.menu_id', 'right');
        $query = $this->db->get()->result_array();
        return $query;
    }

    function get_order_by_id($id)
    {
        return $this->db
        ->select(['orders.id', 'orders.pemesan', 'nomor_order', 'SUM(price * jumlah) as total', 'meja.nomor', 'meja.Posisi'])
        ->join('order_detail', 'orders.id = order_detail.order_id')
        ->join('meja', 'orders.meja = meja.id')
        ->where(['orders.id'=> $id])
        ->get('orders')->row();
        // return $query;
    }
    
    /*
     * Get all orders
     */
    function get_all_orders()
    {
        return $this->db->get('orders')->result_array();
    }

    function get_today_order()
    {
        return $this->db
        ->select(['orders.id', 'orders.pemesan', 'nomor_order', 'SUM(price * jumlah) as total', 'meja.nomor', 'meja.Posisi'])
        ->join('order_detail', 'orders.id = order_detail.order_id')
        ->join('meja', 'orders.meja = meja.id')
        ->where('DATE(tanggal) = CURRENT_DATE()', null)
        ->where('is_pay', 0)
        ->group_by('orders.id')
        ->get('orders')->result_array();
        

    }
    
    /*
     * function to add new order
     */
    function add_order($params)
    {
        $this->db->insert('orders',$params);
        return $this->db->insert_id();
    }

    function get_count_order_today()
    {
        return $this->db->select('count(id) as jumlah')
        ->where('DATE(tanggal) = CURRENT_DATE()', null)
        ->get('orders')->row_array();
    }
    
    /*
     * function to update order
     */
    function update_order($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('orders',$params);
        if($response)
        {
            return ["message"=>"order updated successfully", "code"=> true];
        }
        else
        {
            return ["message"=>"Error occuring while updating order", "code"=> false];
        }
    }
    
    /*
     * function to delete order
     */
    function delete_order($id)
    {
        $response = $this->db->delete('orders',array('id'=>$id));
        if($response)
        {
            return "order deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order";
        }
    }
}
