<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order_detail by id
     */
    function get_order_detail($id)
    {
        return $this->db->get_where('order_detail',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all order_detail
     */
    function get_all_order_detail_by_order_id($order_id)
    {
        return $this->db
            ->get_where('order_detail', ['order_id'=>$order_id])
            ->join('menu', 'menu.id = order_detail.menu_id')
            ->result_array();
    }
    
    /*
     * function to add new order_detail
     */
    function add_order_detail($params)
    {
        $this->db->insert('order_detail',$params);
        return $this->db->insert_id();
    }

    function bulk_insert($data) {
        return $this->db->insert_batch('order_detail', $data); 
    }
    
    /*
     * function to update order_detail
     */
    function update_order_detail($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('order_detail',$params);
        if($response)
        {
            return "order_detail updated successfully";
        }
        else
        {
            return "Error occuring while updating order_detail";
        }
    }
    
    /*
     * function to delete order_detail
     */
    function delete_order_detail($id)
    {
        $response = $this->db->delete('order_detail',array('id'=>$id));
        if($response)
        {
            return "order_detail deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order_detail";
        }
    }
}
